server:
  port: 0

spring:
  application:
    name: service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 183.63.187.149:8848,183.63.187.149:8858,183.63.187.149:8868
        enabled: true
        username: nacos
        password: nacos
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
